### ISSUE TITLE
Consider using elm-syntax-dsl

### ISSUE THREAD

**Issue by MartinSStewart** [ceddlyburge/elm-representer#1]
Hello, I had a look at your project. You mention normalizing code, which I'm guessing means that you're doing something similar to what elm-format does? If that's the case you might want to use elm-syntax-dsl which uses the same elm-syntax's datastructure for code generation. It tries to closely match elm-format which means you might not need to do code normalization yourself.

**Comment by ceddlyburge** [comment]
Hi Martin, thanks for taking an interest :)

I'm always worried when I code that its already been done by somebody else, or that there might be a drastically simpler way of doing things! And sometimes I spent hours looking for something to find out there isn't something. But sometimes I do find a thing. It's always a nervewracking thing.

Anyway, this repo tries to normalize code, so that code that is logically the same is textually the same. Either by outputting code as text or an ast text.

So it turns code like this
https://github.com/ceddlyburge/elm-representer/blob/main/example-originals/Triangle.elm

In to code like this
https://github.com/ceddlyburge/elm-representer/blob/main/examples-normalized/Triangle.elm

Is this something that the elm-syntax-dsl would do?

Cheers, Cedd

**Comment by MartinSStewart** [comment]
Gotcha. In that case, simply parsing the code with elm-syntax and printing it with elm-syntax-dsl won't be enough as it will only get the formatting consistent but it won't standardize identifiers. I don't know of anything that does that so you're probably on the right track.

**Comment by ceddlyburge** [comment]
It looks like it would have been easier to use elm-syntax-dsl from the start though! Unwrapping all the `Node a` type stuff definitely added some annoyance! Maybe I'll have a think about how long it would take to refactor to using that instead.

I was going to use elm-format as a post step actually, to keep the formatting consistent (elm-format seems to be fairly stable), but it would certainly be easier to do it in Elm as part of this code. So it sounds like elm-syntax-dsl and its pretty printer could be a good match for that. It doesn't look like it has an (exported) way to convert an elm-syntax File in to an elm-syntax-dsl File, but it can do it from a string, so I could take the output of the writeFile and write, and push it in to elm-syntax-dsl.

**Comment by MartinSStewart** [comment]
Yeah, I would recommend using `elm-syntax-dsl` over `elm-syntax` for code generation. It produces cleaner code and it's less buggy. I tried replacing the built in Elm.Writer elm-syntax has with an elm-syntax-dsl implementation but unfortunately it would involve breaking changes which we are trying to avoid for now.
